//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FESet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FESet()
        {
            this.OISet = new HashSet<OISet>();
        }
    
        public int IdFE { get; set; }
        public int CreditsBudgetaires { get; set; }
        public int DepensesEngagees { get; set; }
        public int Disponible { get; set; }
        public int EngagementDepensesPropose { get; set; }
        public string NumFe { get; set; }
        public int InfoBC_IdBC { get; set; }
    
        public virtual BCSet BCSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OISet> OISet { get; set; }
    }
}
