//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FESet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FESet()
        {
            this.OISet = new HashSet<OISet>();
        }
    
        public int IdFE { get; set; }
        [Display(Name = "Crédits budgétaires")]
        public int CreditsBudgetaires { get; set; }
        [Display(Name = "Dépenses engagées")]
        public int DepensesEngagees { get; set; }
        [Display(Name = "Disponible")]
        public int Disponible { get; set; }
        [Display(Name = "Engagement de dépense proposé")]
        public int EngagementDepensesPropose { get; set; }
        [Display(Name = "FICHE D'ENGAGEMENT N° ")]
        public string NumFe { get; set; }
        [Display(Name = "Id Bon de commande")]
        public int InfoBC_IdBC { get; set; }

        public virtual BCSet InfoBC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OISet> OISet { get; set; }
    }
}
