//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FournisseurSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FournisseurSet()
        {
            this.ModeleDevisSet = new HashSet<ModeleDevisSet>();
            this.PVJSet = new HashSet<PVJSet>();
            this.ConsultationSet = new HashSet<ConsultationSet>();
            this.PVJSet1 = new HashSet<PVJSet>();
        }
    
        public int IdFournisseur { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public int RC_n { get; set; }
        public string Patente_n { get; set; }
        public int IF_n { get; set; }
        public int CNSS_n { get; set; }
        public string Compte_bancaire_n { get; set; }
        public string ICE { get; set; }
        public string Ville { get; set; }
        public string Banque { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModeleDevisSet> ModeleDevisSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PVJSet> PVJSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationSet> ConsultationSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PVJSet> PVJSet1 { get; set; }
    }
}
