//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ModeleDevisSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModeleDevisSet()
        {
            this.ProduitSet = new HashSet<ProduitSet>();
        }
    
        public int IdModeleDevis { get; set; }
        [Display(Name = "Num Devis")]
        public string NumDevis { get; set; }
        [Display(Name = "Date Devis")]
        public System.DateTime Date { get; set; }
        [Display(Name = "Total")]
        public double Total { get; set; }
        [Display(Name = "Tva")]
        public double Tva { get; set; }
        [Display(Name = "Ttc")]
        public double Ttc { get; set; }
        [Display(Name = "Id Fournisseur")]
        public int InfoFournisseur_IdFournisseur { get; set; }
        [Display(Name = "Id Consultation")]
        public int InfoConsultation_IdConsultation { get; set; }
        [Display(Name = "Info Consultation")]

        public virtual ConsultationSet InfoConsultation { get; set; }
        [Display(Name = "Info Fournisseur")]
        public virtual FournisseurSet InfoFournisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduitSet> ProduitSet { get; set; }
    }
}
