//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OISet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OISet()
        {
            this.OPSet = new HashSet<OPSet>();
            this.PVRSet = new HashSet<PVRSet>();
        }
    
        public int IdOI { get; set; }
        public string NumOi { get; set; }
        public System.DateTime DateOI { get; set; }
        public string NumCompteDebit { get; set; }
        public string VisaControle { get; set; }
        public string VisaCsrs { get; set; }
        public System.DateTime DatePaiement { get; set; }
        public string VisaSordonnateur { get; set; }
        public string VisaTresorierPayeur { get; set; }
        public int InfoFE_IdFE { get; set; }
    
        public virtual FESet InfoFE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPSet> OPSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PVRSet> PVRSet { get; set; }
    }
}
