//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa_Web_Mvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Onssa_ProjetEntities : DbContext
    {
        public Onssa_ProjetEntities()
            : base("name=Onssa_ProjetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BCSet> BCSet { get; set; }
        public virtual DbSet<CommissionSet> CommissionSet { get; set; }
        public virtual DbSet<ConsultationSet> ConsultationSet { get; set; }
        public virtual DbSet<FESet> FESet { get; set; }
        public virtual DbSet<FournisseurSet> FournisseurSet { get; set; }
        public virtual DbSet<GestionCompteSet> GestionCompteSet { get; set; }
        public virtual DbSet<LigneSet> LigneSet { get; set; }
        public virtual DbSet<LrgSet> LrgSet { get; set; }
        public virtual DbSet<ModeleDevisSet> ModeleDevisSet { get; set; }
        public virtual DbSet<MorasseSet> MorasseSet { get; set; }
        public virtual DbSet<OISet> OISet { get; set; }
        public virtual DbSet<OPSet> OPSet { get; set; }
        public virtual DbSet<OVSet> OVSet { get; set; }
        public virtual DbSet<ParagrapheSet> ParagrapheSet { get; set; }
        public virtual DbSet<ProduitSet> ProduitSet { get; set; }
        public virtual DbSet<PVJSet> PVJSet { get; set; }
        public virtual DbSet<PVRSet> PVRSet { get; set; }
    }
}
