//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OPSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPSet()
        {
            this.OVSet = new HashSet<OVSet>();
        }
    
        public int IdOP { get; set; }
        [Display(Name = "Num ordre de paiement")]
        public string NumOP { get; set; }
        [Display(Name = "Date ordre de paiement")]
        public System.DateTime DateOP { get; set; }
        [Display(Name = "Id ordre d'imputation")]
        public int InfoOI_IdOI { get; set; }
        [Display(Name = "Info ordre d'imputation")]

        public virtual OISet InfoOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OVSet> OVSet { get; set; }
    }
}
