//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVSet
    {
        public int IdOV { get; set; }
        public string NumOV { get; set; }
        public string SousOrdonnateur { get; set; }
        public string TresorierPayeur { get; set; }
        public int InfoOP_IdOP { get; set; }
    
        public virtual OPSet OPSet { get; set; }
    }
}
